### ISSUE TITLE
Not supported anymore?

### ISSUE THREAD

**Issue by edestecd** [huit/puppet-pam_access#7]
This module dev appears to not be responding.  Is this module abandoned?
Can I get some feedback on my pull requests?

If I don't hear anything, I'll assume you are not interested and release the updated version on the forge under our Organization.  I hate doing that, but I prefer not pulling from github forever.

**Comment by tfhartmann** [comment]
@edestecd  I think this module is *somewhat* abandoned. @hakamadare cc/ @huit/unix-linux-systems  are there any plans to keep/drop this module?

**Comment by edestecd** [comment]
@robruma , we already released a module to the forge.
If you will maintain this and release a new version, we will take ours down.

**Comment by robruma** [comment]
@edestecd @tfhartmann I'm not sure what the future support provided by HUIT regarding this module may be. I'll reach out to one of the current team members to figure it out.

**Comment by edestecd** [comment]
If no one is interested in Maintaining it, we will adopt it...

**Comment by hakamadare** [comment]
@edestecd you certainly have my blessing to adopt it :)

**Comment by edestecd** [comment]
@hakamadare great can you add a depreciation notice in your README and point folks to:
https://forge.puppet.com/MiamiOH/pam_access
https://github.com/MiamiOH/puppet-pam_access

We are continuing to use and update there....
